CREATE DATABASE `DADOSGOT`;

USE `DADOSGOT`;

CREATE TABLE `EPISODIOS`(
`ID` TINYINT PRIMARY KEY AUTO_INCREMENT,
`TEMPORADA` TINYINT,
`EPISODIO` TINYINT,
`REVIEW_USUARIOS` SMALLINT,
`REWIEW_CRITICA` SMALLINT,
`US_VIEWERS` DECIMAL,
`DURACAO` TINYINT,
`DIRETOR` VARCHAR(25)
);

CREATE TABLE `PERSONAGENS`(
`NOME` VARCHAR(50) PRIMARY KEY,
`APARICOES` SMALLINT
);

CREATE TABLE `CASAS`(
`ID` SMALLINT PRIMARY KEY AUTO_INCREMENT,
`NOME` VARCHAR(50),
`REGIAO` VARCHAR(50)
);

SHOW TABLES;

SELECT * FROM `EPISODIOS`;

SELECT * FROM `PERSONAGENS`;

SELECT * FROM `CASAS`;
