CREATE DATABASE `DADOSGOT`;

USE `DADOSGOT`;

CREATE TABLE `EPISODIOS`(
`ID` TINYINT PRIMARY KEY AUTO_INCREMENT,
`TEMPORADA` TINYINT,
`EPISODIO` TINYINT,
`TITULO` VARCHAR(50),
`LANCAMENTO` VARCHAR(10),
`PONTUACAO` FLOAT,
`VOTOS` INT,
`SINOPSE` TEXT,
`ESCRITOR1` VARCHAR(25),
`ESCRITOR2` VARCHAR(25),
`ESTRELA1` VARCHAR(25),
`ESTRELA2` VARCHAR(25),
`ESTRELA3` VARCHAR(25),
`REVIEW_USUARIOS` SMALLINT,
`REWIEW_CRITICA` SMALLINT,
`US_VIEWERS` SMALLINT,
`DURACAO` TINYINT,
`DIRETOR` VARCHAR(25),
`ORCAMENTO` SMALLINT
);

SHOW TABLES;

SELECT * FROM `EPISODIOS`;

CREATE TABLE `PERSONAGENS`(
`NOME` VARCHAR(50),
`ATOR_ATRIZ` VARCHAR(50) PRIMARY KEY,
`APARICOES` SMALLINT,
`PRIMEIRA_APARICAO` SMALLINT,
`ULTIMA_APARICAO` SMALLINT
);

SELECT * FROM `PERSONAGENS`;

CREATE TABLE `CASAS`(
`ID` SMALLINT PRIMARY KEY AUTO_INCREMENT,
`NOME` VARCHAR(50),
`REGIAO` VARCHAR(50)
);

SELECT * FROM `CASAS`;
